-- No-op: resolves a bad-merge duplicate.
--
-- The "Branch" table, its "Branch_companyId_idx" index and the
-- "Branch_companyId_fkey" foreign key are already created by
-- 20260521183557_modelos_para_autenticacion. Re-creating "Branch" here broke
-- replay ("relation Branch already exists"). The extra "phone" column this
-- branch added is not part of the current schema.
