/**
 * Códigos de error internos reutilizables.
 * Convención: SCREAMING_SNAKE_CASE, valores idénticos a la clave.
 * El frontend puede mapearlos a mensajes localizados sin depender del texto HTTP.
 */
export const ErrorCodes = {
  // Genéricos
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DUPLICATE_RECORD: 'DUPLICATE_RECORD',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  UNAUTHORIZED_COMPANY_ACCESS: 'UNAUTHORIZED_COMPANY_ACCESS',

  // Usuarios / CRM
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',

  // Inventario
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  INVENTORY_NOT_IN_BRANCH: 'INVENTORY_NOT_IN_BRANCH',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  BOX_CLOSED: 'BOX_CLOSED',
  ADJUSTMENT_REASON_REQUIRED: 'ADJUSTMENT_REASON_REQUIRED',
  ADJUSTMENT_REASON_NOT_ALLOWED: 'ADJUSTMENT_REASON_NOT_ALLOWED',

  // Devoluciones
  SALE_NOT_FOUND: 'SALE_NOT_FOUND',
  SALE_NOT_COMPLETED: 'SALE_NOT_COMPLETED',
  RETURN_QUANTITY_EXCEEDED: 'RETURN_QUANTITY_EXCEEDED',
  RETURN_NO_ITEMS: 'RETURN_NO_ITEMS',

  // Ventas / Facturación
  NO_OPEN_CASH_SHIFT: 'NO_OPEN_CASH_SHIFT',
  PAYMENTS_TOTAL_MISMATCH: 'PAYMENTS_TOTAL_MISMATCH',
  CUSTOMER_REQUIRED: 'CUSTOMER_REQUIRED',
  CUSTOMER_REQUIRED_FOR_CREDIT: 'CUSTOMER_REQUIRED_FOR_CREDIT',
  CREDIT_NOTE_NOT_AVAILABLE: 'CREDIT_NOTE_NOT_AVAILABLE',
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
  RESERVATION_NOT_ACTIVE: 'RESERVATION_NOT_ACTIVE',

  // Pagos
  PAYMENT_FAILED: 'PAYMENT_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
