-- No-op: resolves a bad-merge duplicate.
--
-- The full "Company" table (incl. email, phone, slug, isActive, createdAt,
-- updatedAt and the "Company_slug_key" index) is already created by
-- 20260521183557_modelos_para_autenticacion. The original ADD COLUMN / CREATE
-- INDEX statements here came from the old minimal-Company branch and duplicated
-- that work, breaking shadow-DB replay (42701: column already exists).
