-- No-op: resolves a bad-merge artifact.
--
-- This targeted Branch.address / Branch.phone from the superseded branch
-- lineage: "phone" is not part of the current schema, and "address" is already
-- nullable in 20260521183557_modelos_para_autenticacion.
