import {
  ALL_PERMISSION_CODES,
  Permission,
  type PermissionCode,
} from "./permissions.js";
import { TenantRole, type TenantRoleName } from "./roles.js";

/** Matriz rol → permisos para seed y referencia de negocio. */
export const ROLE_PERMISSION_MATRIX: Record<
  TenantRoleName,
  readonly PermissionCode[]
> = {
  [TenantRole.OWNER]: ALL_PERMISSION_CODES,

  [TenantRole.ADMIN]: [
    Permission.USERS_CREATE,
    Permission.USERS_READ,
    Permission.USERS_UPDATE,
    Permission.USERS_ACTIVATE,
    Permission.USERS_DEACTIVATE,
    Permission.USERS_DELETE,
    Permission.EMPLOYEES_CREATE,
    Permission.EMPLOYEES_READ,
    Permission.EMPLOYEES_UPDATE,
    Permission.EMPLOYEES_DELETE,
    Permission.PRODUCTS_CREATE,
    Permission.PRODUCTS_READ,
    Permission.PRODUCTS_UPDATE,
    Permission.PRODUCTS_DELETE,
    Permission.CATEGORIES_CREATE,
    Permission.CATEGORIES_READ,
    Permission.CATEGORIES_UPDATE,
    Permission.CATEGORIES_DELETE,
    Permission.DISCOUNTS_CREATE,
    Permission.DISCOUNTS_READ,
    Permission.DISCOUNTS_UPDATE,
    Permission.DISCOUNTS_DELETE,
    Permission.CUSTOMERS_CREATE,
    Permission.CUSTOMERS_READ,
    Permission.CUSTOMERS_UPDATE,
    Permission.CUSTOMERS_DELETE,
    Permission.SUPPLIERS_CREATE,
    Permission.SUPPLIERS_READ,
    Permission.SUPPLIERS_UPDATE,
    Permission.SUPPLIERS_DELETE,
    Permission.CASH_READ,
    Permission.CASH_MANAGE,
    Permission.BRANCHES_CREATE,
    Permission.BRANCHES_READ,
    Permission.BRANCHES_UPDATE,
    Permission.BRANCHES_DELETE,
    Permission.REPORTS_READ,
  ],

  [TenantRole.MANAGER]: [
    Permission.PRODUCTS_READ,
    Permission.CATEGORIES_READ,
    Permission.DISCOUNTS_READ,
    Permission.SALES_CREATE,
    Permission.SALES_READ,
    Permission.SALES_CANCEL,
    Permission.PURCHASES_CREATE,
    Permission.PURCHASES_READ,
    Permission.CUSTOMERS_CREATE,
    Permission.CUSTOMERS_READ,
    Permission.CUSTOMERS_UPDATE,
    Permission.SUPPLIERS_READ,
    Permission.INVENTORY_READ,
    Permission.INVENTORY_ADJUST,
    Permission.INVENTORY_TRANSFER,
    Permission.CASH_READ,
    Permission.BRANCHES_READ,
    Permission.REPORTS_READ,
  ],

  [TenantRole.CASHIER]: [
    Permission.PRODUCTS_READ,
    Permission.CATEGORIES_READ,
    Permission.DISCOUNTS_READ,
    Permission.SALES_CREATE,
    Permission.SALES_READ,
    Permission.CUSTOMERS_CREATE,
    Permission.CUSTOMERS_READ,
    Permission.CUSTOMERS_UPDATE,
    Permission.CASH_READ,
    Permission.CASH_OPEN,
    Permission.CASH_CLOSE,
  ],

  [TenantRole.INVENTORY_ASSISTANT]: [
    Permission.PRODUCTS_READ,
    Permission.CATEGORIES_READ,
    Permission.SUPPLIERS_READ,
    Permission.INVENTORY_READ,
    Permission.INVENTORY_ADJUST,
    Permission.INVENTORY_TRANSFER,
    Permission.BRANCHES_READ,
  ],
};
