-- No-op: resolves a bad-merge artifact.
--
-- This originally dropped Company.email / Company.phone, but the current schema
-- keeps both as nullable columns (created by
-- 20260521183557_modelos_para_autenticacion), so this drop must not run.
